# Generated by Django 5.1.6 on 2025-02-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
